version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: vatger-training-dev
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "8080:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=vatger_training
      - DB_USERNAME=postgres
      - DB_PASSWORD=12345678
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - MAIL_MAILER=smtp
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - VATSIM_CLIENT_ID=1162
      - VATSIM_CLIENT_SECRET=secret
      - VATSIM_REDIRECT_URI=http://localhost:8080/auth/vatsim/callback
      - VATEUD_TOKEN=token
      - VATEUD_USE_MOCK=false
    depends_on:
      - postgres
      - redis
      - mailhog
    networks:
      - vatger-network

  postgres:
    image: postgres:16-alpine
    container_name: vatger-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: vatger_training
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vatger-network

  redis:
    image: redis:7-alpine
    container_name: vatger-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vatger-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: vatger-mailhog-dev
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - vatger-network

volumes:
  postgres_data:
  redis_data:

networks:
  vatger-network:
    driver: bridge