version: '3.8'

services:
  app:
    build:
      context: .
      target: production
    container_name: vatger-training-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
      - sqlite_data:/var/www/html/database
    ports:
      - "8082:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://training.vatger.de
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_STORE=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_HOST_PROD}
      - MAIL_PORT=${MAIL_PORT_PROD}
      - MAIL_USERNAME=${MAIL_USERNAME_PROD}
      - MAIL_PASSWORD=${MAIL_PASSWORD_PROD}
      - VATSIM_CLIENT_ID=${VATSIM_CLIENT_ID_PROD}
      - VATSIM_CLIENT_SECRET=${VATSIM_CLIENT_SECRET_PROD}
      - VATEUD_TOKEN=${VATEUD_TOKEN_PROD}
    depends_on:
      - redis
    networks:
      - vatger-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vatger-prod.rule=Host(`training.vatger.de`)"
      - "traefik.http.routers.vatger-prod.tls=true"
      - "traefik.http.routers.vatger-prod.tls.certresolver=letsencrypt"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

  redis:
    image: redis:7-alpine
    container_name: vatger-redis-prod
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - vatger-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  scheduler:
    build:
      context: .
      target: production
    container_name: vatger-scheduler-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
      - sqlite_data:/var/www/html/database
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_STORE=redis
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - vatger-network
    command: ["php", "artisan", "schedule:work"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  queue:
    build:
      context: .
      target: production
    container_name: vatger-queue-prod
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
      - sqlite_data:/var/www/html/database
    environment:
      - APP_ENV=production
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - vatger-network
    command: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=90"]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G

volumes:
  app_storage:
  app_cache:
  sqlite_data:
  redis_data:

networks:
  vatger-network:
    driver: bridge